import ireneFixed from "../../assets/characters/irene-fixed-v1.webp";
import ireneMaster from "../../assets/characters/irene-master-v1.webp";
import ireneThinking from "../../assets/characters/irene-thinking-v1.webp";
import type { CharacterContent } from "./types";

export const ireneContent = {
  developer: {
    id: "irene",
    name: "Irene",
    role: "Quiet Assassin",
    passiveName: "Quietly Done",
    passiveRules: "Whenever Verified Work completes a requirement, draw 1 card.",
    startingCardId: "already-fixed",
    accent: "oklch(0.61 0.14 167)",
    art: {
      idle: ireneMaster,
      thinking: ireneThinking,
      success: ireneFixed,
    },
  },
  startingCard: {
    id: "already-fixed",
    ownerId: "irene",
    name: "Already Fixed",
    cost: 1,
    kind: "work",
    discipline: "flexible",
    amount: 3,
    workKind: "verified",
    rules: "Any 3. Verified.",
    tags: ["character", "flexible"],
  },
  rewardCards: [
    {
      id: "quietly-automated",
      ownerId: "irene",
      name: "Quietly Automated",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 1,
      workKind: "verified",
      automation: { kind: "install", power: 1 },
      rules: "Any 1. Install Script 1.",
      tags: ["character", "automation", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "last-10-percent",
      ownerId: "irene",
      name: "Last 10%",
      cost: 0,
      kind: "work",
      discipline: "flexible",
      amount: 2,
      workKind: "verified",
      maxTargetRemaining: 2,
      exhaust: true,
      display: { value: "2", label: "Any", rules: "Only 1–2 Work remaining. Exhaust." },
      rules: "Any 2. Only target a requirement with 2 or less Work remaining. Exhaust.",
      tags: ["character", "exhaust", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "no-fuss",
      ownerId: "irene",
      name: "No Fuss",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 3,
      workKind: "verified",
      focusOnRequirementComplete: 1,
      display: { value: "3", label: "Any", rules: "Complete: +1 Focus." },
      rules: "Any 3. If it completes the requirement, gain 1 Focus.",
      tags: ["character", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "while-im-here",
      ownerId: "irene",
      name: "While I'm Here",
      cost: 1,
      kind: "work",
      discipline: "flexible",
      amount: 2,
      workKind: "verified",
      spilloverVerifiedOnCompletion: 2,
      display: { value: "2+2", label: "Any", rules: "Complete: spill 2 on this Task." },
      rules:
        "Any 2. If it completes the requirement, add 2 Verified Work to another incomplete requirement on that Task.",
      tags: ["character", "flexible", "reward"],
      rarity: "normal",
    },
    {
      id: "quick-study",
      ownerId: "irene",
      name: "Quick Study",
      cost: 1,
      kind: "tactic",
      amount: 0,
      generateLastWorkCopy: true,
      exhaust: true,
      display: { value: "1", label: "Work Copy", rules: "Printed Work only. Costs 0. Exhaust." },
      rules:
        "Generate a zero-cost Verified Work card matching the last Work card's printed discipline and Work. Exhaust.",
      tags: ["character", "exhaust", "reward"],
      rarity: "normal",
    },
    {
      id: "all-sorted",
      ownerId: "irene",
      name: "All Sorted",
      cost: 1,
      kind: "tactic",
      amount: 0,
      completeRequirementsAtMost: 3,
      exhaust: true,
      display: { value: "≤3", label: "Complete", rules: "Every qualifying requirement. Exhaust." },
      rules: "Complete every requirement with 3 or less Work remaining. Exhaust.",
      tags: ["character", "exhaust", "rare", "reward"],
      rarity: "rare",
    },
  ],
} as const satisfies CharacterContent<"irene">;
